apiVersion: getambassador.io/v3alpha1
kind:  TracingService
metadata:
  name:  tracing
  namespace: emissary
spec:
  service: "otelcol-opentelemetry-collector.default.svc.cluster.local:4317"
  driver: opentelemetry
  config:
    service_name: emissary
  sampling:
    overall: 100
  